type: google.api.Service
config_version: 3

http:
  rules:
    - selector: auth.v1.AuthService.SignIn
      post: /api/v1/signin
      body: "*"
    - selector: auth.v1.AuthService.Signup
      post: /api/v1/signup
      body: "*"